### ISSUE TITLE
Swap tape for mocha.

### ISSUE THREAD

**Issue by BerkeleyTrue** [r3dm/thundercats#1]

**Comment by BerkeleyTrue** [comment]
connects #2

**Comment by terakilobyte** [comment]
What assertion library do you want to use?

**Comment by terakilobyte** [comment]
I've got mocha and chai for testing, sinon for method spying, and I've added istanbul to check/display test coverage of the code base. Currently having issues getting mocha to properly test on the observable.

Just a status update.

**Comment by BerkeleyTrue** [comment]
Sweet dude. Keep me updated.

**Comment by terakilobyte** [comment]
https://github.com/terakilobyte/thundercats/blob/mocha/test/store.js

This is how I'm proceeding. If you fork it and look in the  coverage you'll see a nice report.

**Comment by terakilobyte** [comment]
I'm nearly ready to issue a pull request. I haven't added the new tests but it would be nice to get the current tests up into the main repo. Also, I'd like some help with the async tests for Action, they're giving me the business.
