### ISSUE TITLE
Add Relay like features

### ISSUE THREAD

**Issue by BerkeleyTrue** [r3dm/thundercats#28]
Context store will be responsible for creating initial context data to pass to react. This data will be loading into the stores using parent based context.

~~Here is where data-leakage from using singletons will be prevented.~~
edit: In order to support composability, we are going to transition to constructors

Here is what I envision for data fetching. 
- The data fetching should be defined in the store that complements the component.
- The component defines the params needed for itself, ala Relay.
- Data fetching should be initiated in ComponentWillMount as this happens on both server and client. (this can be added to the ObservableStateMixin in a backwards compatible way and in a new HOC that will be created to use with es6 Classes)
- A render to string method must be incorporated into thundercats to facilitate initiating of the data fetching. 

Most of this is inspired by React-Transit which itself is inspired by Relay.

**Comment by terakilobyte** [comment]
Berkeley I'm going to admit we'll need to sit down and pair. Build a simple
todo app so I can see you work everything together. That should also
fulfill our example requirement.
