### ISSUE TITLE
Needs a cool thundercat logo

### ISSUE THREAD

**Issue by vasco3** [r3dm/thundercats#30]

**Comment by BerkeleyTrue** [comment]
Yes! Any designers out there want to help?

**Comment by victorchabbert** [comment]
How is this? 
![thundercats.js](https://cloud.githubusercontent.com/assets/10966568/6673983/1443467a-cc17-11e4-94e3-080f2602d05e.png)

**Comment by BerkeleyTrue** [comment]
Hey @victorchabbert Wow Thanks! wasn't expecting anything, especially not this soon. I was hoping for something closer to the thundercats logo (hopefully not close enough to be infringing on copyrights). I would also like to stick with the Node/IO paradigm of hexagon logos.

**Comment by victorchabbert** [comment]
Alright, I'll try something in a couple of days!

**Comment by morenoh149** [comment]
![thundercat-logo](https://cloud.githubusercontent.com/assets/587438/6746403/e9c43740-ce84-11e4-84f9-a5ee33e61d54.jpg)
inspiration

**Comment by BerkeleyTrue** [comment]
New super cool logo is done and will be displayed shortly!
