### ISSUE TITLE
Improve 'Functional Programming in Javascript'

### ISSUE THREAD

**Issue by morenoh149** [r3dm/thundercats#37]
http://reactive-extensions.github.io/learnrx/ last updated Feb 19th https://github.com/jhusain/learnrx/tree/gh-pages doesn't work for me under Firefox and has several outstanding pull requests.

It would improve thundercats adoption if this resource was as good as possible. Could also be a perfect opportunity to use software developed over at https://github.com/FreeCodeCamp

**Comment by BerkeleyTrue** [comment]
We would definitely benefit from something like this. I am going to close this as it is not a direct issue for thundercats but I would be glad to hear a game plan on this.
