### ISSUE TITLE
Add docs

### ISSUE THREAD

**Issue by BerkeleyTrue** [r3dm/thundercats#6]
Thinking of using docco for documentation inline with source code. Any other suggestions?

**Comment by morenoh149** [comment]
I found this interesting when reading about mocha http://mochajs.org/#doc-reporter don't know how the result compares to docco

**Comment by BerkeleyTrue** [comment]
That's pretty sweet. Looked at the docs generated by Mocha for Supertest and I think Docco has better styling and I prefer the source code to be on the same page ala http://backbonejs.org/

**Comment by BerkeleyTrue** [comment]
I was thinking that we can actually use mocha generated code for the api and docco as a guide.

**Comment by BerkeleyTrue** [comment]
Initial docs up, more to come as soon as tests are converted to mocha
