### ISSUE TITLE
Add stamp descriptor in Actions spec and Store.

### ISSUE THREAD

**Issue by BerkeleyTrue** [r3dm/thundercats#78]
It would be nice to allow stampit specifications in the actions similar to how @troutowicz is doing it for react-stampit: https://github.com/stampit-org/react-stampit/pull/33

Here is the future spec: https://github.com/stampit-org/stamp-specification#the-stamp-descriptor

Current stampit uses different names so I might blacklist all these just to make everything compatible from the beginning.

@joshdmiller what do you think?

**Comment by troutowicz** [comment]
:+1:

**Comment by joshdmiller** [comment]
:+1:
